dist: trusty
sudo: false
matrix:
  include:
  - language: objective-c
    osx_image: xcode10
    before_script:
    - echo 'no need for ./.travisPre.sh'
    script:
    - cd septaJSON
    - xcodebuild clean build -project septaJSON.xcodeproj -scheme septaJSON CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' -quiet
    - xcodebuild test -project septaJSON.xcodeproj -scheme septaJSON -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0'  -enableCodeCoverage  YES -quiet
    







